In [6]:
import torch
inputs = torch.tensor(
    [[0.43, 0.15, 0.89],
     [0.55, 0.87, 0.66],
     [0.57, 0.85, 0.64],
     [0.22, 0.58, 0.33],
     [0.77, 0.25, 0.10],
     [0.05, 0.80, 0.55]]
)
query = inputs[1]
attn_score_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_score_2[i] = torch.dot(query, x_i)
attn_weights_2_tmp = attn_score_2 / attn_score_2.sum()

def softmax_naive(x):
    return torch.exp(x) / torch.exp(x).sum()

print(torch.softmax(attn_score_2, dim=0))

tensor([0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581])


1.计算注意力分数 <br>
2.计算注意力权重 <br>
3.计算上下文向量 <br>

In [ ]:
attn_score = torch.empty(inputs.shape[0], inputs.shape[0])
for i, query in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_score[i][j] += torch.dot(query, x_j)
print(attn_score)

tensor([[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.6310],
        [0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865],
        [0.9422, 1.4754, 1.4570, 0.8296, 0.7154, 1.0605],
        [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
        [0.4576, 0.7070, 0.7154, 0.3474, 0.6654, 0.2935],
        [0.6310, 1.0865, 1.0605, 0.6565, 0.2935, 0.9450]])


In [ ]:
attn_score = inputs @ inputs.T
attn_weights = torch.softmax(attn_score, dim=-1)
print(attn_weights)

tensor([[0.2098, 0.2006, 0.1981, 0.1242, 0.1220, 0.1452],
        [0.1385, 0.2379, 0.2333, 0.1240, 0.1082, 0.1581],
        [0.1390, 0.2369, 0.2326, 0.1242, 0.1108, 0.1565],
        [0.1435, 0.2074, 0.2046, 0.1462, 0.1263, 0.1720],
        [0.1526, 0.1958, 0.1975, 0.1367, 0.1879, 0.1295],
        [0.1385, 0.2184, 0.2128, 0.1420, 0.0988, 0.1896]])


In [25]:
context_vec = attn_weights @ inputs
print(context_vec)

tensor([[0.4421, 0.5931, 0.5790],
        [0.4419, 0.6515, 0.5683],
        [0.4431, 0.6496, 0.5671],
        [0.4304, 0.6298, 0.5510],
        [0.4671, 0.5910, 0.5266],
        [0.4177, 0.6503, 0.5645]])


## 可训练自注意力机制

In [28]:
x_2 = inputs[1]
d_in = inputs.shape[1]
d_out = 2

In [31]:
torch.manual_seed(123)
w_q = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
w_k = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
w_v = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
query_2 = x_2 @ w_q
key_2 = x_2 @ w_k
value_2 = x_2 @ w_v
print(query_2)

tensor([0.4306, 1.4551])


In [ ]:
query = inputs @ w_q
key = inputs @ w_k
value = inputs @ w_v


In [41]:
attn_score_2 = query[1] @ key.T
print(attn_score_2)
d_k = key.shape[-1]
attn_weight_2 = torch.softmax(attn_score_2 / d_k ** 0.5, dim=-1)
print(attn_weight_2)
context_vec_2 = attn_weight_2 @ value
print(context_vec_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])
tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])
tensor([0.3061, 0.8210])
